server:
  servlet:
    context-path: "/course-core"

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tcc-course-db
      username: root
      password: root
      authentication-database: admin